#include "App.h"
#include <commdlg.h>
#include <commctrl.h>
#include <filesystem>
#include <thread>
#include <fstream>
#include "VideoAIVersion.h"

namespace VideoAI {
static constexpr INT_PTR ID_INPUT=1001,ID_MODEL=1003,ID_SCALE=1004,ID_START=1005,ID_STOP=1006,ID_STATUS=1007,ID_PROGRESS=1008,ID_PHASE=1009,ID_METRICS=1010,ID_HEALTH=1011;
static constexpr UINT WM_RENDER_LOG=WM_APP+1, WM_RENDER_METRICS=WM_APP+2;
struct UiMessage { std::wstring text; int percent{}; };
static std::wstring getText(HWND h){std::wstring s(32768,L'\0');int copied=GetWindowTextW(h,s.data(),(int)s.size());if(copied<=0)return{};s.resize((size_t)copied);return s;}
static std::filesystem::path normalizedPath(const std::wstring&text){if(text.empty())return{};std::error_code ec;auto absolute=std::filesystem::absolute(std::filesystem::path(text),ec);if(ec)return std::filesystem::path(text).lexically_normal();auto normalized=std::filesystem::weakly_canonical(absolute,ec);return ec?absolute.lexically_normal():normalized;}
static bool isMetric(const std::wstring&s){return s.rfind(L"IA: ",0)==0;}
static int metricPercent(const std::wstring&s){auto p=s.find(L"IA: ");if(p==std::wstring::npos)return 0;p+=4;auto e=s.find(L'%',p);if(e==std::wstring::npos)return 0;try{return std::stoi(s.substr(p,e-p));}catch(...){return 0;}}
static std::filesystem::path uniqueOutput(const std::filesystem::path&base,int scale){auto stem=base.stem().wstring()+L"_V" VIDEOAI_VERSION L"_"+std::to_wstring(scale)+L"x";auto p=base.parent_path()/(stem+L".mp4");if(!std::filesystem::exists(p))return p;for(int i=2;i<1000;i++){auto q=base.parent_path()/(stem+L"_"+std::to_wstring(i)+L".mp4");if(!std::filesystem::exists(q))return q;}return{};}
App::App(HINSTANCE i):instance_(i){}App::~App(){stop();}
int App::run(int show){INITCOMMONCONTROLSEX icc{sizeof(icc),ICC_PROGRESS_CLASS};InitCommonControlsEx(&icc);WNDCLASSW wc{};wc.hInstance=instance_;wc.lpfnWndProc=&App::wndProc;wc.lpszClassName=L"VideoAIEnhancer";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);window_=CreateWindowExW(0,wc.lpszClassName,L"VideoAI Enhancer - V" VIDEOAI_VERSION,WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1040,760,nullptr,nullptr,instance_,this);createControls();ShowWindow(window_,show);UpdateWindow(window_);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return (int)msg.wParam;}
void App::createControls(){auto st=[&](const wchar_t*t,int x,int y,int w,int h){CreateWindowW(L"STATIC",t,WS_CHILD|WS_VISIBLE,x,y,w,h,window_,nullptr,instance_,nullptr);};st(L"Vídeo de entrada",30,25,130,25);CreateWindowW(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_BORDER,165,22,680,28,window_,(HMENU)ID_INPUT,instance_,nullptr);CreateWindowW(L"BUTTON",L"Selecionar",WS_CHILD|WS_VISIBLE,855,22,120,28,window_,(HMENU)(ID_INPUT+100),instance_,nullptr);st(L"Modelo",30,70,100,25);HWND m=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,165,67,300,180,window_,(HMENU)ID_MODEL,instance_,nullptr);SendMessageW(m,CB_ADDSTRING,0,(LPARAM)L"Real-ESRGAN General v3");SendMessageW(m,CB_SETCURSEL,0,0);st(L"Escala",500,70,70,25);HWND sc=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,570,67,120,180,window_,(HMENU)ID_SCALE,instance_,nullptr);SendMessageW(sc,CB_ADDSTRING,0,(LPARAM)L"2x");SendMessageW(sc,CB_ADDSTRING,0,(LPARAM)L"4x");SendMessageW(sc,CB_SETCURSEL,1,0);st(L"Monitoramento",30,110,110,25);phase_=CreateWindowW(L"STATIC",L"Fase: Pronto",WS_CHILD|WS_VISIBLE,165,110,360,25,window_,(HMENU)ID_PHASE,instance_,nullptr);metrics_=CreateWindowW(L"STATIC",L"Progresso: 0% | FPS: - | ETA: - | Tempo: 00:00",WS_CHILD|WS_VISIBLE,530,110,445,25,window_,(HMENU)ID_METRICS,instance_,nullptr);progress_=CreateWindowW(PROGRESS_CLASSW,L"",WS_CHILD|WS_VISIBLE,30,145,945,24,window_,(HMENU)ID_PROGRESS,instance_,nullptr);SendMessageW(progress_,PBM_SETRANGE,0,MAKELPARAM(0,100));SendMessageW(progress_,PBM_SETPOS,0,0);health_=CreateWindowW(L"STATIC",L"Saúde: aguardando renderização",WS_CHILD|WS_VISIBLE,30,178,945,25,window_,(HMENU)ID_HEALTH,instance_,nullptr);CreateWindowW(L"BUTTON",L"Melhorar vídeo",WS_CHILD|WS_VISIBLE,30,215,180,42,window_,(HMENU)ID_START,instance_,nullptr);CreateWindowW(L"BUTTON",L"Parar",WS_CHILD|WS_VISIBLE,220,215,120,42,window_,(HMENU)ID_STOP,instance_,nullptr);st(L"LOG DE RENDERIZAÇÃO",30,275,500,25);CreateWindowW(L"EDIT",L"Pronto. Faça um teste curto primeiro.\r\n",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_MULTILINE|ES_AUTOVSCROLL|ES_READONLY|WS_VSCROLL,30,305,945,350,window_,(HMENU)ID_STATUS,instance_,nullptr);}
void App::appendLog(const std::wstring&s){if(!window_)return;HWND box=GetDlgItem(window_,ID_STATUS);int n=GetWindowTextLengthW(box);SendMessageW(box,EM_SETSEL,n,n);SendMessageW(box,EM_REPLACESEL,FALSE,(LPARAM)(s+L"\r\n").c_str());SendMessageW(box,EM_SCROLL,SB_BOTTOM,0);}
void App::publish(const std::wstring&level,const std::wstring&message){renderLog_.write(level,message);if(!window_)return;auto*p=new UiMessage{L"["+level+L"] "+message,metricPercent(message)};UINT msg=isMetric(message)?WM_RENDER_METRICS:WM_RENDER_LOG;if(!PostMessageW(window_,msg,0,(LPARAM)p))delete p;}
void App::start(){if(worker_.joinable()){appendLog(L"[WARN] Já existe uma renderização em andamento.");return;}const auto storedInput=inputVideo_;const std::wstring editText=getText(GetDlgItem(window_,ID_INPUT));std::filesystem::path in=storedInput;if(in.empty()&&!editText.empty())in=normalizedPath(editText);if(!in.empty())in=normalizedPath(in.wstring());if(!in.empty())inputVideo_=in;appendLog(L"[DEBUG] Caminho armazenado: "+storedInput.wstring());appendLog(L"[DEBUG] Caminho lido do EDIT: "+editText);appendLog(L"[DEBUG] Caminho efetivamente usado: "+in.wstring());std::error_code pathError;if(in.empty()){appendLog(L"[ERRO] Selecione um vídeo primeiro.");return;}if(!std::filesystem::exists(in,pathError)||pathError){appendLog(L"[ERRO] Vídeo não encontrado: "+in.wstring());return;}if(!ffmpeg_.available()){appendLog(L"[ERRO] FFmpeg não encontrado ao lado do EXE nem no PATH.");return;}
 VideoInfo vi;std::wstring probeErr;if(!ffmpeg_.probe(in,vi,probeErr)){appendLog(L"[ERRO] Pré-verificação de vídeo falhou: "+probeErr);return;}int sel=(int)SendMessageW(GetDlgItem(window_,ID_SCALE),CB_GETCURSEL,0,0);int scale=sel==0?2:4;long long pixels=(long long)vi.width*scale*vi.height*scale;if(pixels>40000000LL){appendLog(L"[ERRO] A saída excederia 40 MP por frame. Use 2x ou um vídeo menor.");return;}std::wstring nvdiag;bool nv=ffmpeg_.canUseNvenc(nvdiag);appendLog(nv?L"[INFO] Encoder disponível: NVIDIA NVENC.":L"[INFO] NVENC indisponível; usando CPU. "+nvdiag);auto out=uniqueOutput(in,scale);if(out.empty()){appendLog(L"[ERRO] Não foi possível criar um nome de saída livre.");return;}if(!renderLog_.open())appendLog(L"[WARN] Log em arquivo indisponível; monitoramento visual continuará.");else appendLog(L"[INFO] Log: "+renderLog_.path().wstring());stop_=false;SendMessageW(progress_,PBM_SETPOS,0,0);SetWindowTextW(phase_,L"Fase: preparando");SetWindowTextW(health_,L"Saúde: pré-verificações OK");
 worker_=std::thread([this,in,out,scale,vi,nv](){try{publish(L"INFO",L"Pré-verificações concluídas. Preparando modelo.");ModelSpec spec{"realesr-general-x4v3",L"Real-ESRGAN General v3","https://huggingface.co/notaneimu/onnx-image-models/resolve/e4cafda1199bcec66a76b10025aafb655cd0ff30/realesr-general-x4v3.onnx?download=true","e8db65652ed421c2f8c92645d8f6fc6b07fd2868a916fdaa1a99c8d28091f097",4};std::wstring status;if(!models_.ensureModel(spec,status)){publish(L"ERROR",status);return;}Enhancer e;EnhanceConfig cfg;cfg.scale=scale;cfg.tile=256;cfg.tilePad=16;std::wstring err;if(!e.process(in,out,models_.modelPath(spec),ffmpeg_.locate(),vi,nv,cfg,[this](const std::wstring&s){publish(L"INFO",s);},stop_,err)){publish(stop_?L"WARN":L"ERROR",err.empty()?(stop_?L"Processamento interrompido.":L"Falha sem diagnóstico adicional."):err);return;}publish(L"SUCCESS",L"CONCLUÍDO. Arquivo validado: "+out.wstring());}catch(const std::exception&ex){std::string m=ex.what();publish(L"ERROR",L"Falha isolada no worker: "+std::wstring(m.begin(),m.end()));}catch(...){publish(L"ERROR",L"Falha isolada no worker, sem detalhes do componente.");}});}
void App::stop(){stop_=true;if(worker_.joinable())worker_.join();}
LRESULT CALLBACK App::wndProc(HWND h,UINT msg,WPARAM wp,LPARAM lp){App*self=(App*)GetWindowLongPtrW(h,GWLP_USERDATA);if(msg==WM_NCCREATE){auto*c=(CREATESTRUCTW*)lp;self=(App*)c->lpCreateParams;SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)self);self->window_=h;}return self?self->handle(h,msg,wp,lp):DefWindowProcW(h,msg,wp,lp);}
LRESULT App::handle(HWND h,UINT msg,WPARAM wp,LPARAM lp){if(msg==WM_COMMAND){int id=LOWORD(wp);int notification=HIWORD(wp);if(id==ID_INPUT&&notification==EN_CHANGE){inputVideo_=normalizedPath(getText((HWND)lp));}else if(id==ID_INPUT+100&&notification==BN_CLICKED){OPENFILENAMEW ofn{};wchar_t buf[1024]{};ofn.lStructSize=sizeof(ofn);ofn.hwndOwner=h;ofn.lpstrFile=buf;ofn.nMaxFile=1024;ofn.lpstrFilter=L"Vídeos\0*.mp4;*.mkv;*.mov;*.avi;*.webm\0Todos\0*.*\0";ofn.Flags=OFN_FILEMUSTEXIST|OFN_PATHMUSTEXIST;if(GetOpenFileNameW(&ofn)){inputVideo_=normalizedPath(buf);SetWindowTextW(GetDlgItem(h,ID_INPUT),inputVideo_.wstring().c_str());}}else if(id==ID_START&&notification==BN_CLICKED)start();else if(id==ID_STOP&&notification==BN_CLICKED)stop();}if(msg==WM_RENDER_LOG){auto*p=(UiMessage*)lp;if(p){appendLog(p->text);if(p->text.rfind(L"[ERROR]",0)==0)SetWindowTextW(health_,L"Saúde: ERRO DETECTADO");else if(p->text.rfind(L"[SUCCESS]",0)==0)SetWindowTextW(health_,L"Saúde: renderização concluída");delete p;}return 0;}if(msg==WM_RENDER_METRICS){auto*p=(UiMessage*)lp;if(p){SendMessageW(progress_,PBM_SETPOS,p->percent,0);SetWindowTextW(metrics_,p->text.c_str());SetWindowTextW(phase_,L"Fase: processamento IA");delete p;}return 0;}if(msg==WM_DESTROY){stop();PostQuitMessage(0);return 0;}return DefWindowProcW(h,msg,wp,lp);}
}
