#include "Enhancer.h"
#include <windows.h>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstring>
#include <sstream>
#include <iomanip>

namespace VideoAI {
namespace {
static std::wstring utf8w(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);if(n<=0)return std::wstring(s.begin(),s.end());std::wstring o(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n);return o;}
struct ProcessPipe {HANDLE process=nullptr,thread=nullptr,inWrite=nullptr,errRead=nullptr;~ProcessPipe(){close();}void close(){if(inWrite){CloseHandle(inWrite);inWrite=nullptr;}if(errRead){CloseHandle(errRead);errRead=nullptr;}if(thread){CloseHandle(thread);thread=nullptr;}if(process){CloseHandle(process);process=nullptr;}}};
static std::wstring quote(const std::filesystem::path&p){return L"\""+p.wstring()+L"\"";}
static bool startEncoder(const std::filesystem::path&exe,const std::filesystem::path&original,const std::filesystem::path&output,double fps,bool nvenc,ProcessPipe&p,std::wstring&err){
    SECURITY_ATTRIBUTES sa{};sa.nLength=sizeof(sa);sa.bInheritHandle=TRUE;HANDLE inR=nullptr,inW=nullptr,erR=nullptr,erW=nullptr;if(!CreatePipe(&inR,&inW,&sa,0)||!CreatePipe(&erR,&erW,&sa,0)){err=L"Falha ao criar o canal do encoder FFmpeg.";return false;}SetHandleInformation(inW,HANDLE_FLAG_INHERIT,0);SetHandleInformation(erR,HANDLE_FLAG_INHERIT,0);
    std::wstring codec=nvenc?L"h264_nvenc":L"libx264";std::wstring args=L"-hide_banner -loglevel error -nostdin -y -f image2pipe -vcodec ppm -framerate "+std::to_wstring(fps)+L" -i - -i "+quote(original)+L" -map 0:v:0 -map 1:a? -c:v "+codec+(nvenc?L" -preset p4 -cq 18":L" -preset fast -crf 18 -threads 6")+L" -pix_fmt yuv420p -c:a aac -b:a 192k -shortest "+quote(output);
    STARTUPINFOW si{};si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES;si.hStdInput=inR;si.hStdOutput=GetStdHandle(STD_OUTPUT_HANDLE);si.hStdError=erW;PROCESS_INFORMATION pi{};std::wstring cmd=quote(exe)+L" "+args;std::vector<wchar_t> buf(cmd.begin(),cmd.end());buf.push_back(L'\0');
    if(!CreateProcessW(nullptr,buf.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&pi)){DWORD e=GetLastError();CloseHandle(inR);CloseHandle(inW);CloseHandle(erR);CloseHandle(erW);err=L"Falha ao iniciar o encoder FFmpeg. Código do Windows: "+std::to_wstring(e);return false;}
    CloseHandle(inR);CloseHandle(erW);p.process=pi.hProcess;p.thread=pi.hThread;p.inWrite=inW;p.errRead=erR;return true;
}
static bool writeAll(HANDLE h,const unsigned char*d,size_t n,std::atomic_bool&stop){size_t off=0;while(off<n){if(stop.load())return false;DWORD w=0;DWORD want=(DWORD)std::min<size_t>(n-off,1<<20);if(!WriteFile(h,d+off,want,&w,nullptr)||w==0)return false;off+=w;}return true;}
static bool writeFrame(HANDLE h,int w,int hgt,const std::vector<unsigned char>&rgb,std::atomic_bool&stop){std::string hdr="P6\n"+std::to_string(w)+" "+std::to_string(hgt)+"\n255\n";if(!writeAll(h,(const unsigned char*)hdr.data(),hdr.size(),stop))return false;return writeAll(h,rgb.data(),rgb.size(),stop);}
static std::wstring drainError(HANDLE h){std::string s;DWORD avail=0;while(PeekNamedPipe(h,nullptr,0,nullptr,&avail,nullptr)&&avail){char b[4096];DWORD got=0;DWORD want=std::min<DWORD>(avail,(DWORD)sizeof(b));if(!ReadFile(h,b,want,&got,nullptr)||!got)break;s.append(b,b+got);}return utf8w(s);}
}
Enhancer::Enhancer():env_(ORT_LOGGING_LEVEL_WARNING,"VideoAI"),opts_(){opts_.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);opts_.SetIntraOpNumThreads(0);opts_.SetInterOpNumThreads(1);}
bool Enhancer::load(const std::filesystem::path&p,std::wstring&err){try{session_=std::make_unique<Ort::Session>(env_,p.wstring().c_str(),opts_);return true;}catch(const Ort::Exception&e){err=utf8w(e.what());return false;}catch(const std::exception&e){err=utf8w(e.what());return false;}}
Enhancer::Frame Enhancer::crop(const Frame&src,int x,int y,int w,int h){Frame o;o.w=w;o.h=h;o.rgb.resize((size_t)w*h*3);for(int yy=0;yy<h;yy++)std::memcpy(o.rgb.data()+(size_t)yy*w*3,src.rgb.data()+((size_t)(y+yy)*src.w+x)*3,(size_t)w*3);return o;}
void Enhancer::copyCrop(const Frame&src,Frame&dst,int srcX,int srcY,int w,int h,int dstX,int dstY){for(int yy=0;yy<h;yy++)std::memcpy(dst.rgb.data()+((size_t)(dstY+yy)*dst.w+dstX)*3,src.rgb.data()+((size_t)(srcY+yy)*src.w+srcX)*3,(size_t)w*3);}
void Enhancer::downsample2x(const Frame&src,Frame&dst){dst.w=src.w/2;dst.h=src.h/2;dst.rgb.resize((size_t)dst.w*dst.h*3);for(int y=0;y<dst.h;y++)for(int x=0;x<dst.w;x++)for(int c=0;c<3;c++){size_t a=((size_t)(2*y)*src.w+2*x)*3+c;size_t b=a+3;size_t d=a+(size_t)src.w*3;size_t e=d+3;dst.rgb[((size_t)y*dst.w+x)*3+c]=(unsigned char)((src.rgb[a]+src.rgb[b]+src.rgb[d]+src.rgb[e])/4);}}
Enhancer::Frame Enhancer::inferTile(const Frame&in,const EnhanceConfig&cfg){(void)cfg;if(!session_)throw std::runtime_error("Sessão ONNX não carregada.");const int h=in.h,w=in.w;std::vector<float> tensor((size_t)3*h*w);for(int y=0;y<h;y++)for(int x=0;x<w;x++){size_t p=((size_t)y*w+x)*3;tensor[(size_t)y*w+x]=in.rgb[p]/255.0f;tensor[(size_t)h*w+y*w+x]=in.rgb[p+1]/255.0f;tensor[(size_t)2*h*w+y*w+x]=in.rgb[p+2]/255.0f;}
    std::vector<int64_t> shape{1,3,h,w};Ort::AllocatorWithDefaultOptions alloc;auto inName=session_->GetInputNameAllocated(0,alloc);auto outName=session_->GetOutputNameAllocated(0,alloc);const char*ins[]={inName.get()};const char*outs[]={outName.get()};auto mem=Ort::MemoryInfo::CreateCpu(OrtArenaAllocator,OrtMemTypeDefault);auto val=Ort::Value::CreateTensor<float>(mem,tensor.data(),tensor.size(),shape.data(),shape.size());auto result=session_->Run(Ort::RunOptions{nullptr},ins,&val,1,outs,1);auto info=result[0].GetTensorTypeAndShapeInfo();auto os=info.GetShape();const float*ptr=result[0].GetTensorData<float>();if(os.size()!=4||os[0]!=1||os[1]!=3||os[2]<=0||os[3]<=0||!ptr)throw std::runtime_error("Saída do modelo ONNX inválida.");Frame out;out.h=(int)os[2];out.w=(int)os[3];out.rgb.resize((size_t)out.w*out.h*3);for(int y=0;y<out.h;y++)for(int x=0;x<out.w;x++){size_t q=(size_t)y*out.w+x;for(int c=0;c<3;c++){float v=ptr[(size_t)c*out.w*out.h+q];v=std::clamp(v,0.0f,1.0f);out.rgb[q*3+c]=(unsigned char)std::lround(v*255.0f);}}return out;}

bool Enhancer::process(const std::filesystem::path&input,const std::filesystem::path&output,const std::filesystem::path&model,const std::filesystem::path&ffmpeg,const VideoInfo&info,bool nvenc,const EnhanceConfig&cfg,const std::function<void(const std::wstring&)>&progress,std::atomic_bool&stop,std::wstring&errorOut){
    errorOut.clear();std::wstring err;if(!load(model,err)){errorOut=L"Falha ao carregar o modelo ONNX: "+err;return false;}if(info.width<=0||info.height<=0){errorOut=L"Dimensões do vídeo inválidas.";return false;}if(cfg.scale!=2&&cfg.scale!=4){errorOut=L"Escala inválida. Use 2x ou 4x.";return false;}long long fw=(long long)info.width*cfg.scale,fh=(long long)info.height*cfg.scale;if(fw>100000||fh>100000||fw*fh>40000000LL){errorOut=L"A saída excede o limite seguro de 40 megapixels por frame.";return false;}
    ProcessPipe enc;if(!startEncoder(ffmpeg,input,output,info.fps,nvenc,enc,err)){errorOut=err;return false;}auto started=std::chrono::steady_clock::now();long long frames=0;double lastReport=0;
    Ffmpeg fm;bool ok=fm.decodePpmPipe(input,info,stop,[&](int w,int h,const std::vector<unsigned char>&rgb,std::wstring&cbErr){
        if(stop.load()){cbErr=L"Processamento interrompido pelo usuário.";return false;}Frame inputFrame{w,h,rgb};Frame out{(int)fw,(int)fh,std::vector<unsigned char>((size_t)fw*fh*3)};int tile=std::max(64,std::min(1024,cfg.tile));int pad=std::max(0,std::min(cfg.tilePad,tile/4));
        try{for(int y=0;y<h;y+=tile)for(int x=0;x<w;x+=tile){if(stop.load()){cbErr=L"Processamento interrompido durante a inferência.";return false;}int x0=std::max(0,x-pad),y0=std::max(0,y-pad),x1=std::min(w,x+tile+pad),y1=std::min(h,y+tile+pad);Frame t=crop(inputFrame,x0,y0,x1-x0,y1-y0);Frame up=inferTile(t,cfg);int modelScale=4;int cw=std::min(tile,w-x),ch=std::min(tile,h-y);int ox=(x-x0)*modelScale,oy=(y-y0)*modelScale;if(ox+cw*modelScale>up.w||oy+ch*modelScale>up.h){cbErr=L"O modelo ONNX retornou dimensão incompatível com o tile.";return false;}Frame crop4=crop(up,ox,oy,cw*modelScale,ch*modelScale);if(cfg.scale==4)copyCrop(crop4,out,0,0,cw*4,ch*4,x*4,y*4);else{Frame crop2;downsample2x(crop4,crop2);copyCrop(crop2,out,0,0,cw*2,ch*2,x*2,y*2);}}
            if(!writeFrame(enc.inWrite,out.w,out.h,out.rgb,stop)){cbErr=stop.load()?L"Processamento interrompido pelo usuário.":L"FFmpeg encerrou o encoder antes de receber todos os frames.";return false;}
        }catch(const Ort::Exception&e){cbErr=L"ONNX Runtime falhou durante a inferência: "+utf8w(e.what());return false;}catch(const std::exception&e){cbErr=L"Falha no processamento do frame: "+utf8w(e.what());return false;}catch(...){cbErr=L"Falha desconhecida no processamento do frame.";return false;}
        frames++;if(progress){auto now=std::chrono::steady_clock::now();double elapsed=std::chrono::duration<double>(now-started).count();if(elapsed-lastReport>=0.75){double speed=elapsed>0?frames/elapsed:0;double total=info.duration>0?info.duration*info.fps:0;int pct=total>0?std::min(99,(int)(frames*100/total)):0;double eta=speed>0&&total>frames?(total-frames)/speed:0;std::wstringstream ss;ss<<L"IA: "<<pct<<L"% | Frame "<<frames; if(total>0)ss<<L"/"<<(long long)total;ss<<L" | FPS: "<<std::fixed<<std::setprecision(1)<<speed<<L" | ETA: ";if(eta>0)ss<<std::setprecision(0)<<eta<<L" s";else ss<<L"calculando";ss<<L" | Encoder: "<<(nvenc?L"NVENC":L"CPU");progress(ss.str());lastReport=elapsed;}}return true;
    },err);
    if(!ok){enc.close();std::error_code ec;std::filesystem::remove(output,ec);errorOut=err.empty()?L"Falha no fluxo FFmpeg/IA.":err;return false;}
    if(enc.inWrite){CloseHandle(enc.inWrite);enc.inWrite=nullptr;}DWORD wr=WaitForSingleObject(enc.process,120000);if(wr==WAIT_TIMEOUT){TerminateProcess(enc.process,3);err=L"FFmpeg excedeu o tempo de encerramento e foi finalizado.";enc.close();std::error_code ec;std::filesystem::remove(output,ec);errorOut=err;return false;}DWORD code=1;GetExitCodeProcess(enc.process,&code);std::wstring diag=drainError(enc.errRead);enc.close();std::error_code ec;if(stop.load()){std::filesystem::remove(output,ec);errorOut=L"Processamento interrompido pelo usuário.";return false;}if(code!=0){std::filesystem::remove(output,ec);errorOut=L"FFmpeg falhou na exportação. Código "+std::to_wstring(code)+(diag.empty()?L"":L". "+diag);return false;}if(!std::filesystem::exists(output,ec)||std::filesystem::file_size(output,ec)<=4096){errorOut=L"FFmpeg terminou, mas o arquivo final não foi validado.";return false;}if(progress)progress(L"IA: 100% | Exportação concluída com validação do arquivo.");return true;
}
}
